### PR TITLE
Make sqlite and redis dependencies optional

### PR DESCRIPTION
**Pull request by tohojo**
**Purpose of proposed changes**

Make it possible to run the daemon without the aiosqlite and aioredis packages
installed, as long as those backends are not used by the running config.

This makes it easier for distribution packaging, where the package can have
optional dependencies on the libraries instead of always forcing an install of
them.

**Essential steps taken**

Change setup.py to declare the sqlite and redis dependencies as optional
features.

### CODE REVIEW

**Comment by Snawoot** [comment]
Thanks for that! It is really useful change and I thought about it, but I wasn't determined enough about it.

I can merge this pull request right now, but I think we also need to update installation notes in documentation and Dockerfile which is intented to provide full-featured version of package. Would you like to add more commits into your PR to make it more complete or you'd like to leave it to me to carry out?

**Comment by tohojo** [comment]
Snawoot <notifications@github.com> writes:

> Thanks for that! It is really useful change and I thought about it,
> but I wasn't determined enough about it.
>
> I can merge this pull request right now, but I think we also need to
> update installation notes in documentation and Dockerfile which is
> intented to provide full-featured version of package. Would you like
> to add more commits into your PR to make it more complete or you'd
> like to leave it to me to carry out?

I'm not much of a docker person, so if you don't mind doing it, please
go ahead :)

**Comment by Snawoot** [comment]
OK! Thanks again!

**Comment by tohojo** [comment]
Snawoot <notifications@github.com> writes:

> OK! Thanks again!

You're welcome! And thanks for the quick merge :)

**Pull request merged**
